# Generated by Django 4.1.3 on 2022-11-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comentario', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_curso', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=500)),
                ('horario', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Dificultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difi_nom', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Epocas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Epoca_nom', models.CharField(max_length=14)),
                ('epoca_desc', models.TextField(max_length=100)),
                ('fecha_epoca', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Herramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_herramienta', models.CharField(max_length=10)),
                ('desc_herramienta', models.TextField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Impartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_imp', models.CharField(max_length=30)),
                ('año_experiencia', models.PositiveIntegerField()),
                ('idioma_imp', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Manualidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=80)),
                ('procedimiento', models.TextField(max_length=600)),
                ('video', models.URLField(blank=True, null=True, verbose_name='Dirección Web')),
            ],
        ),
    ]
