# Generated by Django 4.1.3 on 2022-11-18 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raquel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualidades',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impartidor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manualidades',
            name='herramientas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herramientas', to='raquel.herramientas'),
        ),
        migrations.AddField(
            model_name='epocas',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='raquel.curso'),
        ),
        migrations.AddField(
            model_name='epocas',
            name='dificultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dificultad', to='raquel.dificultad'),
        ),
        migrations.AddField(
            model_name='curso',
            name='impartidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impartidor', to='raquel.impartidor'),
        ),
        migrations.AddField(
            model_name='curso',
            name='manualidades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manualidades', to='raquel.manualidades'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='N_Curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentCurso', to='raquel.curso'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='N_Epoca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentEpoca', to='raquel.manualidades'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='N_Manualidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentMan', to='raquel.manualidades'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='NombreU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
