# Generated by Django 4.1.3 on 2022-11-18 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raquel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='N_Epoca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentEpoca', to='raquel.epocas'),
        ),
    ]
