# Generated by Django 4.1.3 on 2022-11-19 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raquel', '0005_epocas_impartidor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='N_Curso',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='N_Epoca',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='N_Manualidad',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='nom_curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='raquel.curso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='epocas',
            name='impartidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imparti', to=settings.AUTH_USER_MODEL),
        ),
    ]
