# Generated by Django 4.1.3 on 2022-11-20 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raquel', '0007_comentariosm_comentariose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentariose',
            old_name='Comentario',
            new_name='ComentarioE',
        ),
        migrations.RenameField(
            model_name='comentariose',
            old_name='NombreU',
            new_name='NombreUE',
        ),
        migrations.RenameField(
            model_name='comentariosm',
            old_name='Comentario',
            new_name='ComentarioM',
        ),
        migrations.RenameField(
            model_name='comentariosm',
            old_name='NombreU',
            new_name='NombreUM',
        ),
        migrations.AlterField(
            model_name='comentariose',
            name='nom_epocas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarioE', to='raquel.epocas'),
        ),
        migrations.AlterField(
            model_name='comentariosm',
            name='nom_manualidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarioM', to='raquel.manualidades'),
        ),
    ]
