# Generated by Django 4.1.3 on 2022-12-09 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raquel', '0008_rename_comentario_comentariose_comentarioe_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComentariosE',
        ),
    ]
