# Generated by Django 4.1.4 on 2022-12-09 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raquel', '0009_delete_comentariose'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentariosE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComentarioE', models.CharField(max_length=200)),
                ('NombreUE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nom_epocas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarioE', to='raquel.epocas')),
            ],
        ),
    ]
