# Generated by Django 4.1.4 on 2022-12-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raquel', '0010_comentariose'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualidades',
            name='poster',
            field=models.ImageField(blank=True, upload_to='poster/'),
        ),
    ]
