# Generated by Django 4.1.4 on 2022-12-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raquel', '0011_manualidades_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='precio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
