# Generated by Django 4.1.4 on 2022-12-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raquel', '0012_curso_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='posterC',
            field=models.ImageField(blank=True, upload_to='poster/'),
        ),
        migrations.AddField(
            model_name='epocas',
            name='posterE',
            field=models.ImageField(blank=True, upload_to='poster/'),
        ),
    ]
