# Generated by Django 4.1.4 on 2022-12-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raquel', '0013_curso_posterc_epocas_postere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'permissions': [('admin_generico', 'Puede editar y crear Cursos'), ('suscriptor', 'Pago de suscripcion, ver Cursos')]},
        ),
    ]
