# Generated by Django 4.1.4 on 2022-12-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raquel', '0014_alter_curso_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manualidades',
            options={'permissions': [('admin_generico', 'Puede editar y crear Manualidades'), ('suscriptor', 'Pago de suscripcion, ver video Manualidades')]},
        ),
    ]
