# Generated by Django 4.1.4 on 2022-12-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raquel', '0016_manualidades_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manualidades',
            options={},
        ),
    ]
