# Generated by Django 4.1.4 on 2022-12-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raquel', '0018_alter_manualidades_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manualidades',
            options={'permissions': [('admin_genericoManualidades', 'Puede editar y crear Manualidades'), ('suscriptorManualidades', 'Pago de suscripcion, ver video Manualidades')]},
        ),
    ]
